const { chromium } = require('/Users/whtnybiatch/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('fs');
const base = 'http://127.0.0.1:8765';
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.screenshot({ path: '.data/clip-assistant-desktop.png', fullPage: true });
  await page.locator('#path-fallback').count().catch(() => 0);
  await page.locator('summary').click();
  await page.locator('#path-input').fill('/Users/whtnybiatch/Documents/ChatGPT/steve barlet/clip-assistant/.runtime/sample.mp4');
  await page.locator('#path-btn').click();
  await page.locator('input[value="local"]').check();
  await page.locator('#analyze-btn').click();
  await page.waitForFunction(() => document.querySelector('#job-stage')?.textContent.includes('READY'), null, { timeout: 120000 });
  await page.locator('.clip-card').first().click();
  await page.waitForTimeout(500);
  const preview = await page.locator('#video').evaluate((video, range) => ({ currentTime: video.currentTime, paused: video.paused, start: Number(range) }), await page.locator('#ranges input').nth(0).inputValue());
  if (preview.paused || preview.currentTime < preview.start - .5) throw new Error(`candidate preview did not start: ${JSON.stringify(preview)}`);
  await page.locator('#close-editor').click();
  const closedPreview = await page.locator('#video').evaluate(video => ({ paused: video.paused, selected: Boolean(document.querySelector('.clip-card.selected')) }));
  if (!closedPreview.paused || closedPreview.selected) throw new Error(`closing editor did not clean up playback: ${JSON.stringify(closedPreview)}`);
  await page.locator('.clip-card').first().click();
  const editorBackground = await page.locator('#clip-editor').evaluate(editor => getComputedStyle(editor).backgroundColor);
  if (editorBackground === 'transparent' || editorBackground.endsWith(', 0)')) throw new Error(`editor is not solid: ${editorBackground}`);
  const editorBounds = await page.locator('#clip-editor').evaluate(editor => ({ bottom: editor.getBoundingClientRect().bottom, nextTop: editor.nextElementSibling?.getBoundingClientRect().top }));
  if (editorBounds.nextTop < editorBounds.bottom - 1) throw new Error(`editor overlaps candidates: ${JSON.stringify(editorBounds)}`);
  await page.locator('#ranges input').nth(0).fill('40');
  await page.locator('#ranges input').nth(1).fill('70');
  await page.locator('#export-btn').click();
  await page.waitForFunction(() => [...document.querySelectorAll('#exports a')].some(a => a.textContent.includes('Download 480p')), null, { timeout: 120000 });
  await page.waitForFunction(() => document.querySelector('#job-stage')?.textContent.includes('READY'), null, { timeout: 120000 });
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#exports a').first().click()]);
  await download.saveAs('.data/clip-assistant-export.mp4');
  await page.screenshot({ path: '.data/clip-assistant-workspace.png', fullPage: true });
  const desktop = { stage: await page.locator('#job-stage').textContent(), clips: await page.locator('.clip-card').count(), exports: await page.locator('#exports a').count(), bytes: fs.statSync('.data/clip-assistant-export.mp4').size };
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mobile.goto(base, { waitUntil: 'networkidle' });
  await mobile.screenshot({ path: '.data/clip-assistant-mobile.png', fullPage: true });
  console.log(JSON.stringify({ desktop, mobileTitle: await mobile.title() }));
  await browser.close();
})().catch(error => { console.error(error); process.exitCode = 1; });
